import React, { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { supabase } from '../lib/supabase';
import useAuthStore from '../hooks/useAuth';
import { formatDateTime } from '../lib/constants';
import { HiOutlineArrowLeft, HiOutlineDownload } from 'react-icons/hi';
import { Chart as ChartJS, ArcElement, Tooltip, Legend, CategoryScale, LinearScale, BarElement } from 'chart.js';
import { Doughnut, Bar } from 'react-chartjs-2';
ChartJS.register(ArcElement,Tooltip,Legend,CategoryScale,LinearScale,BarElement);
const cols=['#10B981','#F97316','#8B5CF6','#F59E0B','#3B82F6','#EC4899','#14B8A6','#6366F1','#F43F5E','#84CC16'];
export default function SurveyAnalytics(){
  const{id}=useParams();const{profile}=useAuthStore();const[sv,setSv]=useState(null);const[qs,sQs]=useState([]);const[rs,sRs]=useState([]);const[ans,sAns]=useState([]);const[loading,setLoading]=useState(true);
  useEffect(()=>{if(profile?.id)load();},[id,profile?.id]);
  async function load(){try{const{data:s}=await supabase.from('surveys').select('*').eq('id',id).single();setSv(s);const{data:q}=await supabase.from('survey_questions').select('*').eq('survey_id',id).order('sort_order');sQs(q||[]);const{data:r}=await supabase.from('survey_responses').select('*').eq('survey_id',id).order('started_at');sRs(r||[]);if(r?.length){const{data:a}=await supabase.from('survey_answers').select('*').in('response_id',r.map(x=>x.id));sAns(a||[]);}}catch(e){console.error(e);}finally{setLoading(false);}}
  const total=rs.length;const done=rs.filter(r=>r.status==='completed').length;const rate=total?Math.round((done/total)*100):0;
  function getQA(q){const qa=ans.filter(a=>a.question_id===q.id);if(!qa.length)return null;if(['single_choice','dropdown','yes_no'].includes(q.question_type)){const c={};qa.forEach(a=>{const v=a.answer_value||'—';c[v]=(c[v]||0)+1;});return{type:'doughnut',data:{labels:Object.keys(c).map(k=>(q.options||[]).find(o=>o.value===k)?.label||k),datasets:[{data:Object.values(c),backgroundColor:cols.slice(0,Object.keys(c).length),borderWidth:0}]},total:qa.length};}if(q.question_type==='multiple_choice'){const c={};qa.forEach(a=>(a.answer_json||[]).forEach(v=>{c[v]=(c[v]||0)+1;}));return{type:'bar',data:{labels:Object.keys(c).map(k=>(q.options||[]).find(o=>o.value===k)?.label||k),datasets:[{data:Object.values(c),backgroundColor:cols,borderRadius:8,barThickness:28}]},total:qa.length};}if(['rating','scale'].includes(q.question_type)){const vs=qa.map(a=>parseInt(a.answer_value)||0).filter(Boolean);const avg=vs.length?(vs.reduce((a,b)=>a+b,0)/vs.length).toFixed(1):0;const mx=q.question_type==='rating'?5:10;const d={};for(let i=1;i<=mx;i++)d[i]=0;vs.forEach(v=>{if(d[v]!==undefined)d[v]++;});return{type:'bar',data:{labels:Object.keys(d),datasets:[{data:Object.values(d),backgroundColor:cols,borderRadius:4,barThickness:20}]},avg,total:vs.length};}return{type:'text',items:qa.map(a=>a.answer_value).filter(Boolean),total:qa.length};}
  function csv(){const h=['#','Status','Email','Started','Completed',...qs.map(q=>q.question_text)];const rows=rs.map((r,i)=>{const ra=ans.filter(a=>a.response_id===r.id);return[i+1,r.status,r.respondent_email||'',r.started_at,r.completed_at||'',...qs.map(q=>{const a=ra.find(x=>x.question_id===q.id);return a?.answer_value||(a?.answer_json?JSON.stringify(a.answer_json):'');})];});const c=[h,...rows].map(r=>r.map(c=>`"${String(c).replace(/"/g,'""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([c],{type:'text/csv'}));a.download=`${sv?.title||'survey'}.csv`;a.click();}
  const opts={responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{cornerRadius:8}}};
  if(loading)return<div className="text-center py-20 text-muted">Loading...</div>;if(!sv)return<div className="text-center py-20 text-muted">Not found</div>;
  return(<div>
    <div className="flex items-end justify-between mb-10"><div><Link to={`/surveys/${id}/edit`} className="text-sm text-muted hover:text-accent flex items-center gap-1 mb-2"><HiOutlineArrowLeft className="w-4 h-4"/>Back to survey</Link><h1 className="text-3xl font-extrabold text-dark tracking-tight">{sv.title}</h1></div><button onClick={csv} className="px-5 py-2.5 rounded-full text-sm font-semibold border border-gray-200 text-dark hover:bg-gray-100 flex items-center gap-2"><HiOutlineDownload className="w-4 h-4"/>Export</button></div>
    <div className="grid grid-cols-3 gap-4 mb-12">{[{l:'Responses',v:total,c:'bg-dark'},{l:'Completed',v:done,c:'bg-accent'},{l:'Rate',v:`${rate}%`,c:'bg-accent'}].map((s,i)=>(<div key={i} className="bg-white rounded-2xl border border-gray-100 p-6"><p className="text-4xl font-extrabold text-dark">{s.v}</p><p className="text-muted text-sm mt-2">{s.l}</p><div className={`w-8 h-1 rounded-full mt-3 ${s.c}`}/></div>))}</div>
    <h2 className="text-sm font-bold text-muted uppercase tracking-[0.15em] mb-6">Question Breakdown</h2>
    <div className="space-y-5">{qs.map((q,i)=>{const a=getQA(q);return(<div key={q.id} className="bg-white rounded-2xl border border-gray-100 p-6"><div className="flex items-start gap-3 mb-5"><span className="text-xs font-bold text-muted mt-0.5">{i+1}.</span><div><p className="text-base font-bold text-dark">{q.question_text}</p><p className="text-xs text-muted">{a?.total||0} responses</p></div></div>{!a?<p className="text-xs text-gray-300 italic">No responses</p>:a.type==='doughnut'?(<div className="flex items-center gap-8"><div className="w-[150px] h-[150px]"><Doughnut data={a.data} options={{...opts,cutout:'65%'}}/></div><div className="space-y-2 flex-1">{a.data.labels.map((l,j)=>(<div key={j} className="flex items-center justify-between"><div className="flex items-center gap-2"><div className="w-3 h-3 rounded-full" style={{backgroundColor:cols[j]}}/><span className="text-sm text-muted">{l}</span></div><span className="text-sm font-bold text-dark">{a.data.datasets[0].data[j]}</span></div>))}</div></div>):a.type==='bar'?(<div>{a.avg&&<p className="text-sm text-muted mb-3">Average: <span className="font-extrabold text-dark text-xl">{a.avg}</span></p>}<div className="h-[180px]"><Bar data={a.data} options={{...opts,scales:{y:{beginAtZero:true,ticks:{stepSize:1}},x:{grid:{display:false}}}}}/></div></div>):(<div className="max-h-44 overflow-y-auto space-y-2">{a.items.slice(0,20).map((r,j)=>(<div key={j} className="text-sm text-dark bg-soft rounded-xl px-4 py-2.5">{r}</div>))}{a.items.length>20&&<p className="text-xs text-muted">+{a.items.length-20} more</p>}</div>)}</div>);})}</div>
    <div className="bg-white rounded-2xl border border-gray-100 p-6 mt-8"><h3 className="text-sm font-bold text-muted uppercase tracking-[0.15em] mb-4">Responses</h3>{!rs.length?<p className="text-xs text-gray-300">None</p>:<div className="overflow-x-auto"><table className="w-full"><thead><tr className="border-b border-gray-200">{['#','Status','Email','Started','Completed'].map(h=><th key={h} className="text-left py-3 px-3 text-[11px] font-bold uppercase tracking-wider text-muted">{h}</th>)}</tr></thead><tbody>{rs.slice(0,50).map((r,i)=>(<tr key={r.id} className="border-b border-gray-100 hover:bg-soft/50"><td className="py-3 px-3 text-muted text-xs">{i+1}</td><td className="py-3 px-3"><span className={r.status==='completed'?'badge-active':r.status==='in_progress'?'badge bg-blue-50 text-blue-600':'badge-closed'}>{r.status}</span></td><td className="py-3 px-3 text-muted text-xs">{r.respondent_email||'—'}</td><td className="py-3 px-3 text-muted text-xs">{formatDateTime(r.started_at)}</td><td className="py-3 px-3 text-muted text-xs">{r.completed_at?formatDateTime(r.completed_at):'—'}</td></tr>))}</tbody></table></div>}</div>
  </div>);
}
