import React, { useState, useEffect } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { supabase } from '../lib/supabase';
import useAuthStore from '../hooks/useAuth';
import { QUESTION_TYPES, hasPermission, SURVEY_STATUS, formatDate, isExpired } from '../lib/constants';
import toast from 'react-hot-toast';
import { HiOutlinePlus, HiOutlineTrash, HiOutlineArrowUp, HiOutlineArrowDown, HiOutlineSave, HiOutlineX, HiOutlineLink, HiOutlineChartBar, HiOutlinePlay, HiOutlinePause, HiOutlineRefresh, HiOutlineShare } from 'react-icons/hi';
const hasO=t=>['single_choice','multiple_choice','dropdown'].includes(t);
const inp="w-full px-4 py-3 bg-white border border-gray-200 rounded-xl text-dark text-sm placeholder:text-gray-400 focus:outline-none focus:border-accent transition-colors";

export default function SurveyEdit(){
  const{id}=useParams();const{profile}=useAuthStore();const nav=useNavigate();
  const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[sv,setSv]=useState(null);const[qs,sQs]=useState([]);const[tab,setTab]=useState('details');
  const[shareOpen,setShareOpen]=useState(false);const[shares,setShares]=useState([]);const[users,setUsers]=useState([]);

  useEffect(()=>{if(profile?.id)load();},[id,profile?.id]);
  async function load(){try{const{data:s,error}=await supabase.from('surveys').select('*').eq('id',id).single();if(error)throw error;setSv({...s,expires_at:s.expires_at?new Date(s.expires_at).toISOString().slice(0,16):''});const{data:q}=await supabase.from('survey_questions').select('*').eq('survey_id',id).order('sort_order');sQs((q||[]).map(x=>({...x,_id:x.id})));const{data:sh}=await supabase.from('survey_shares').select('*,user:user_profiles!shared_with(full_name,email)').eq('survey_id',id);setShares(sh||[]);const{data:u}=await supabase.from('user_profiles').select('id,full_name,email,role');setUsers(u||[]);}catch(e){console.error(e);toast.error('Failed');nav('/surveys');}finally{setLoading(false);}}
  const s=(k,v)=>setSv(p=>({...p,[k]:v}));const sQ=(tid,k,v)=>sQs(a=>a.map(q=>q._id===tid?{...q,[k]:v}:q));
  const addQ=()=>sQs(a=>[...a,{_id:'new_'+Math.random().toString(36).slice(2),question_text:'',question_type:'short_text',options:[],is_required:false,description:''}]);
  const delQ=async tid=>{if(qs.length<=1)return toast.error('Need ≥1');if(!tid.startsWith('new_'))await supabase.from('survey_questions').delete().eq('id',tid);sQs(a=>a.filter(q=>q._id!==tid));};
  const moveQ=(tid,d)=>sQs(a=>{const i=a.findIndex(q=>q._id===tid);if((d===-1&&i===0)||(d===1&&i===a.length-1))return a;const b=[...a];[b[i],b[i+d]]=[b[i+d],b[i]];return b;});
  const addOpt=tid=>sQs(a=>a.map(q=>q._id===tid?{...q,options:[...(q.options||[]),{label:'',value:''}]}:q));
  const sOpt=(tid,i,v)=>sQs(a=>a.map(q=>{if(q._id!==tid)return q;const o=[...(q.options||[])];o[i]={label:v,value:v.toLowerCase().replace(/\s+/g,'_')};return{...q,options:o};}));
  const delOpt=(tid,i)=>sQs(a=>a.map(q=>q._id!==tid?q:{...q,options:q.options.filter((_,j)=>j!==i)}));
  async function save(){if(!sv.title.trim())return toast.error('Title required');setBusy(true);try{const{data,error}=await supabase.from('surveys').update({title:sv.title,description:sv.description||null,welcome_message:sv.welcome_message||null,thank_you_message:sv.thank_you_message||null,expires_at:sv.expires_at||null,allow_anonymous:sv.allow_anonymous,require_email:sv.require_email,show_progress_bar:sv.show_progress_bar,theme_color:sv.theme_color}).eq('id',id).select().single();if(error)throw error;if(!data)throw new Error('Update failed');for(let i=0;i<qs.length;i++){const q=qs[i];const d={survey_id:id,question_text:q.question_text,question_type:q.question_type,options:hasO(q.question_type)?q.options:null,is_required:q.is_required,description:q.description||null,sort_order:i};if(q._id.startsWith('new_')){const{error:e}=await supabase.from('survey_questions').insert(d);if(e)throw e;}else{const{error:e}=await supabase.from('survey_questions').update(d).eq('id',q._id);if(e)throw e;}}toast.success('Saved!');await load();}catch(e){console.error(e);toast.error(e.message||'Failed');}finally{setBusy(false);}}
  async function chg(st){const u={status:st};if(st==='active'&&isExpired(sv.expires_at)){const d=prompt('Days:','7');if(!d)return;const x=new Date();x.setDate(x.getDate()+parseInt(d));u.expires_at=x.toISOString();}await supabase.from('surveys').update(u).eq('id',id);toast.success('Updated');load();}
  async function share(uid){await supabase.from('survey_shares').upsert({survey_id:id,shared_with:uid,shared_by:profile.id,permission:'view_analytics'});toast.success('Shared');load();}
  function copyLink(){navigator.clipboard.writeText(`${window.location.origin}/s/${sv.slug}`);toast.success('Copied!');}
  if(loading)return<div className="text-center py-20 text-muted">Loading...</div>;
  if(!sv)return<div className="text-center py-20 text-muted">Not found</div>;
  const tabs=[{id:'details',l:'Details'},{id:'questions',l:`Questions (${qs.length})`},{id:'settings',l:'Settings'}];
  return(<div className="max-w-3xl mx-auto">
    <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4 mb-10">
      <div><div className="flex items-center gap-3 mb-1"><h1 className="text-3xl font-extrabold text-dark tracking-tight">{sv.title}</h1><span className={SURVEY_STATUS[sv.status]?.class}>{SURVEY_STATUS[sv.status]?.label}</span></div>
        <div className="flex items-center gap-4 text-xs text-muted">{sv.expires_at&&<span className={isExpired(sv.expires_at)?'text-red-500':''}>{isExpired(sv.expires_at)?'Expired':`Exp ${formatDate(sv.expires_at)}`}</span>}<button onClick={copyLink} className="hover:text-accent flex items-center gap-1"><HiOutlineLink className="w-3.5 h-3.5"/>Copy link</button></div></div>
      <div className="flex flex-wrap gap-2">
        {sv.status!=='active'&&<button onClick={()=>chg('active')} className="px-4 py-2 rounded-full text-xs font-semibold bg-accent text-white hover:bg-accent/80"><HiOutlinePlay className="w-3.5 h-3.5 inline mr-1"/>Activate</button>}
        {sv.status==='active'&&<button onClick={()=>chg('paused')} className="px-4 py-2 rounded-full text-xs font-semibold border border-gray-200 text-dark hover:bg-gray-100"><HiOutlinePause className="w-3.5 h-3.5 inline mr-1"/>Pause</button>}
        {['expired','closed'].includes(sv.status)&&hasPermission(profile?.role,'resume_survey')&&<button onClick={()=>chg('active')} className="px-4 py-2 rounded-full text-xs font-semibold bg-accent text-white"><HiOutlineRefresh className="w-3.5 h-3.5 inline mr-1"/>Resume</button>}
        <Link to={`/surveys/${id}/analytics`} className="px-4 py-2 rounded-full text-xs font-semibold border border-gray-200 text-dark hover:bg-gray-100 inline-flex items-center gap-1"><HiOutlineChartBar className="w-3.5 h-3.5"/>Analytics</Link>
        <button onClick={()=>setShareOpen(true)} className="px-4 py-2 rounded-full text-xs font-semibold border border-gray-200 text-dark hover:bg-gray-100"><HiOutlineShare className="w-3.5 h-3.5 inline mr-1"/>Share</button>
        <button onClick={save} disabled={busy} className="px-5 py-2 rounded-full text-xs font-semibold bg-dark text-white hover:bg-accent transition-colors disabled:opacity-40"><HiOutlineSave className="w-3.5 h-3.5 inline mr-1"/>{busy?'Saving...':'Save'}</button>
      </div></div>
    <div className="flex gap-2 p-1.5 bg-gray-100 rounded-full mb-8">{tabs.map(t=><button key={t.id} onClick={()=>setTab(t.id)} className={`flex-1 py-2.5 rounded-full text-sm font-medium transition-all ${tab===t.id?'bg-white text-dark shadow-sm':'text-muted'}`}>{t.l}</button>)}</div>
    {tab==='details'&&(<div className="space-y-5">
      <div><label className="text-xs font-semibold text-muted uppercase tracking-wider block mb-2">Title *</label><input value={sv.title} onChange={e=>s('title',e.target.value)} className={`${inp} !text-lg font-semibold`}/></div>
      <div><label className="text-xs font-semibold text-muted uppercase tracking-wider block mb-2">Description</label><textarea value={sv.description||''} onChange={e=>s('description',e.target.value)} className={inp} rows={2}/></div>
      <div><label className="text-xs font-semibold text-muted uppercase tracking-wider block mb-2">Welcome</label><textarea value={sv.welcome_message||''} onChange={e=>s('welcome_message',e.target.value)} className={inp} rows={2}/></div>
      <div><label className="text-xs font-semibold text-muted uppercase tracking-wider block mb-2">Thank you</label><textarea value={sv.thank_you_message||''} onChange={e=>s('thank_you_message',e.target.value)} className={inp} rows={2}/></div>
      <div className="grid grid-cols-2 gap-5"><div><label className="text-xs font-semibold text-muted uppercase tracking-wider block mb-2">Expires</label><input type="datetime-local" value={sv.expires_at} onChange={e=>s('expires_at',e.target.value)} className={inp}/></div><div><label className="text-xs font-semibold text-muted uppercase tracking-wider block mb-2">Theme</label><div className="flex gap-2"><input type="color" value={sv.theme_color||'#10B981'} onChange={e=>s('theme_color',e.target.value)} className="w-10 h-10 rounded-xl border border-gray-200 cursor-pointer"/><input value={sv.theme_color||''} onChange={e=>s('theme_color',e.target.value)} className={`${inp} flex-1 font-mono`}/></div></div></div></div>)}
    {tab==='questions'&&(<div className="space-y-4">{qs.map((q,i)=>(<div key={q._id} className="bg-white rounded-2xl border border-gray-200 p-6"><div className="flex items-center justify-between mb-4"><span className="text-xs font-bold text-muted">{i+1}.</span><div className="flex gap-1"><button onClick={()=>moveQ(q._id,-1)} disabled={i===0} className="p-1.5 rounded-lg hover:bg-gray-100 disabled:opacity-20"><HiOutlineArrowUp className="w-4 h-4"/></button><button onClick={()=>moveQ(q._id,1)} disabled={i===qs.length-1} className="p-1.5 rounded-lg hover:bg-gray-100 disabled:opacity-20"><HiOutlineArrowDown className="w-4 h-4"/></button><button onClick={()=>delQ(q._id)} className="p-1.5 rounded-lg hover:bg-red-50 text-red-500"><HiOutlineTrash className="w-4 h-4"/></button></div></div>
      <input value={q.question_text} onChange={e=>sQ(q._id,'question_text',e.target.value)} className={`${inp} mb-2 font-medium`} placeholder="Question..."/><input value={q.description||''} onChange={e=>sQ(q._id,'description',e.target.value)} className={`${inp} mb-3`} placeholder="Helper text..."/>
      <div className="flex gap-3 items-center"><select value={q.question_type} onChange={e=>sQ(q._id,'question_type',e.target.value)} className={`${inp} flex-1`}>{QUESTION_TYPES.map(t=><option key={t.value} value={t.value}>{t.icon} {t.label}</option>)}</select><label className="flex items-center gap-2 text-sm text-muted cursor-pointer whitespace-nowrap"><input type="checkbox" checked={q.is_required} onChange={e=>sQ(q._id,'is_required',e.target.checked)} className="rounded border-gray-300 text-accent w-4 h-4"/>Required</label></div>
      {hasO(q.question_type)&&(<div className="mt-4 pl-4 border-l-2 border-accent/20 space-y-2">{(q.options||[]).map((o,j)=>(<div key={j} className="flex items-center gap-2"><div className="w-4 h-4 rounded-full border-2 border-gray-300 flex-shrink-0"/><input value={o.label} onChange={e=>sOpt(q._id,j,e.target.value)} className={`${inp} py-2 flex-1`} placeholder={`Option ${j+1}`}/><button onClick={()=>delOpt(q._id,j)} className="p-1 text-red-400"><HiOutlineX className="w-4 h-4"/></button></div>))}<button onClick={()=>addOpt(q._id)} className="text-sm font-semibold text-accent flex items-center gap-1"><HiOutlinePlus className="w-3.5 h-3.5"/>Add option</button></div>)}
    </div>))}<button onClick={addQ} className="w-full py-4 border-2 border-dashed border-gray-300 rounded-2xl text-sm font-medium text-muted hover:border-accent hover:text-accent transition-colors flex items-center justify-center gap-2"><HiOutlinePlus className="w-5 h-5"/>Add Question</button></div>)}
    {tab==='settings'&&(<div className="space-y-3">{[{k:'allow_anonymous',l:'Anonymous',d:'No identity needed'},{k:'require_email',l:'Require email',d:'Ask before starting'},{k:'show_progress_bar',l:'Progress bar',d:'Show completion'}].map(x=>(<label key={x.k} className="flex items-center justify-between p-5 rounded-2xl bg-white border border-gray-200 cursor-pointer hover:border-accent/30 transition-colors"><div><p className="text-sm font-semibold text-dark">{x.l}</p><p className="text-xs text-muted mt-0.5">{x.d}</p></div><input type="checkbox" checked={sv[x.k]} onChange={e=>s(x.k,e.target.checked)} className="rounded border-gray-300 text-accent w-5 h-5"/></label>))}</div>)}
    {shareOpen&&(<div className="fixed inset-0 bg-dark/20 backdrop-blur-sm z-50 flex items-center justify-center p-4" onClick={()=>setShareOpen(false)}><div className="bg-white rounded-3xl shadow-lg w-full max-w-sm p-6" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between mb-4"><h3 className="text-lg font-bold text-dark">Share analytics</h3><button onClick={()=>setShareOpen(false)} className="p-1 rounded-lg hover:bg-gray-100"><HiOutlineX className="w-5 h-5"/></button></div><p className="text-xs text-muted mb-4">Within your organization only.</p><div className="space-y-2 max-h-60 overflow-y-auto">{users.filter(u=>u.id!==profile.id).map(u=>{const shared=shares.some(x=>x.shared_with===u.id);return(<div key={u.id} className="flex items-center justify-between p-3 rounded-xl bg-soft"><div><p className="text-sm font-medium text-dark">{u.full_name||u.email}</p><p className="text-[11px] text-muted">{u.role}</p></div>{shared?<span className="text-[11px] font-bold text-accent">Shared ✓</span>:<button onClick={()=>share(u.id)} className="text-[11px] font-bold text-dark hover:text-accent">Share</button>}</div>);})}</div></div></div>)}
  </div>);
}
